disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_unwrapping
  - force_try

opt_in_rules:
  - empty_count
  - colon
  - comma
  - control_statement
  - closure_end_indentation

included:
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods

line_length:
  warning: 200
  error: 250
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length:
    warning: 1
    error: 3
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - URL

reporter: "xcode"
